In [1]:
#working with numpy array
import numpy as np

In [2]:
arr1=[2,4,6,8]
print(type(arr1))


<class 'list'>


In [3]:
#now convert list in to array
narr1=np.array(arr1)
print(type(narr1))
print(narr1)

<class 'numpy.ndarray'>
[2 4 6 8]


In [4]:
#working with Two dimensional array
arr2=[[1,2,3,4],[5,6,7,8]]


In [5]:
narr2=np.array(arr2)
print(narr2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
matrix_null=np.zeros((2,2))
print(matrix_null)

[[0. 0.]
 [0. 0.]]


In [7]:
same=np.full((3,3),9)

In [8]:
print(same)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [9]:
diagonal=np.eye(3,3)
print(diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
## Vector Operations
## addition
## multiplication 
##It is array manipulation
a=np.array([1,2,3])
b=np.array([2,4,6])
sum=a+b
print(sum)
print(a-a)

[3 6 9]
[0 0 0]


In [11]:
print(b+10)

[12 14 16]


In [12]:
print(a*b)

[ 2  8 18]


In [13]:
print(np.dot(a,b))

28


In [14]:
##Now we start about matrix manipulation
##It is strictly 2D array 


In [15]:
p=np.matrix([[2,3],[1,1]])
q=np.matrix([[5,4],[1,2]])

In [16]:
print(p*q)
print(p)

[[13 14]
 [ 6  6]]
[[2 3]
 [1 1]]


In [17]:
m=np.matrix([[2,3,4],[3,4,5],[1,4,1]])
n=np.matrix([[6,3,3],[5,4,5],[1,2,2]])

In [18]:
print(m)


[[2 3 4]
 [3 4 5]
 [1 4 1]]


In [19]:
print(m*n)

[[31 26 29]
 [43 35 39]
 [27 21 25]]


In [20]:
print(np.multiply(p,p))

[[4 9]
 [1 1]]


In [21]:
#Inverse of Matrix
from numpy.linalg import inv

In [22]:
print(inv(p))

[[-1.  3.]
 [ 1. -2.]]


In [23]:
print(p.T)

[[2 1]
 [3 1]]


In [24]:
#Solving simultaneous linear equation using numpy
#if x-y=-1
#2x+y=4
#so x will have value of x=1 and y=2

In [28]:
A=np.array([[2,1],[1,-1]])
B=np.array([4,-1])
A_inverse=np.linalg.inv(A)
A_inverse.dot(B)


array([1., 2.])

In [29]:
#adding arrays using numpy
a=[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]

In [30]:
num_a=np.array(a)

In [31]:
num_a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [35]:
num_a.sum()

40

sum

In [39]:
num_a.sum(axis=1)
num_a.sum(axis=0)

array([ 4,  8, 12, 16])